In [1]:
#importing relevant libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from datetime import datetime

In [3]:

#importing traffic collisions dataset from DataLA (https://data.lacity.org/Public-Safety/Crime-Data-from-2010-to-2019/63jg-8b9z/about_data
#                                                  https://data.lacity.org/Public-Safety/Crime-Data-from-2020-to-Present/2nrs-mtv8/about_data)
df1 = pd.read_csv('/content/Crime_Data_from_2010_to_2019_20250219 (2).csv')
df2 = pd.read_csv('/content/Crime_Data_from_2020_to_Present_20250219.csv')

df1.head(2)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,02/20/2010 12:00:00 AM,02/20/2010 12:00:00 AM,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,09/13/2010 12:00:00 AM,09/12/2010 12:00:00 AM,45,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962

In [4]:
#comparing column names to ensure proper concatenation of the two datasets
columns_df1 = set(df1.columns)
columns_df2 = set(df2.columns)

common_columns = columns_df1.intersection(columns_df2)
unique_columns_df1 = columns_df1.difference(columns_df2)
unique_columns_df2 = columns_df2.difference(columns_df1)

#printing common and unique columns
print("Common columns:", common_columns)
print("\nColumns unique to df1:", unique_columns_df1)
print("Columns unique to df2:", unique_columns_df2)

Common columns: {'AREA NAME', 'Vict Age', 'Vict Descent', 'Part 1-2', 'Mocodes', 'Crm Cd 2', 'DATE OCC', 'Premis Desc', 'Vict Sex', 'Crm Cd 4', 'Status', 'Date Rptd', 'Premis Cd', 'Crm Cd', 'Cross Street', 'Crm Cd 3', 'DR_NO', 'TIME OCC', 'LAT', 'Status Desc', 'Rpt Dist No', 'Weapon Used Cd', 'Crm Cd Desc', 'LOCATION', 'Weapon Desc', 'LON', 'Crm Cd 1'}

Columns unique to df1: {'AREA '}
Columns unique to df2: {'AREA'}

In [5]:
#renaming the unique columns from each dataset to match
df1.rename(columns={'AREA ': 'AREA'}, inplace = True)

#combining matching datasets into one cohesive dataset for easier analysis
df = pd.concat([df1, df2], ignore_index=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3138119 entries, 0 to 3138118
Data columns (total 28 columns):
 #   Column          Dtype
---  ------          -----
 0   DR_NO           int64
 1   Date Rptd       object
 2   DATE OCC        object
 3   TIME OCC        int64
 4   AREA            int64
 5   AREA NAME       object
 6   Rpt Dist No     int64
 7   Part 1-2        int64
 8   Crm Cd          int64
 9   Crm Cd Desc     object
 10  Mocodes         object
 11  Vict Age        int64
 12  Vict Sex        object
 13  Vict Descent    object
 14  Premis Cd       float64
 15  Premis Desc     object
 16  Weapon Used Cd  float64
 17  Weapon Desc     object
 18  Status          object
 19  Status Desc     object
 20  Crm Cd 1        float64
 21  Crm Cd 2        float64
 22  Crm Cd 3        float64
 23  Crm Cd 4        float64
 24  LOCATION        object
 25  Cross Street    object
 26  LAT             float64
 27  LON             float64
dtypes: float64(8), int64(7), object(13)
memory usage: 670.4+ MB

In [6]:
#converting date and time data into datetime formats for easier analysis
df['Date Rptd'] = pd.to_datetime(df['Date Rptd'])
df['DATE OCC'] = pd.to_datetime(df['DATE OCC'])

#adding leading zeroes for military time conversions
df['TIME OCC'] = df['TIME OCC'].astype(str).str.zfill(4)

<ipython-input-6-c8095e39632a>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date Rptd'] = pd.to_datetime(df['Date Rptd'])
<ipython-input-6-c8095e39632a>:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DATE OCC'] = pd.to_datetime(df['DATE OCC'])

In [7]:
df.head(2)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,1307355,2010-02-20,2010-02-20,1350,13,Newton,1385,2,900,VIOLATION OF COURT ORDER,...,AA,Adult Arrest,900.0,NaN,NaN,NaN,300 E GAGE AV,NaN,33.9825,-118.2695
1,11401303,2010-09-13,2010-09-12,0045,14,Pacific,1485,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,SEPULVEDA BL,MANCHESTER AV,33.9599,-118.3962

In [8]:
#replacing column names for a standarized naming convention
df.columns = df.columns.str.replace(' ', '_').str.lower()
df.rename(columns={'lat': 'latitude',
                   'lon': 'longitude',
                   'rpt_dist_no':'rdistrict_no',
                   'crm_cd':'crime_code',
                   'crm_cd_desc':'crime_desc',
                   'premis_cd':'premise_code',
                   'weapon_used_cd':'weapon_code'}, inplace = True)
df.drop(columns={'part_1-2'}, inplace = True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3138119 entries, 0 to 3138118
Data columns (total 27 columns):
 #   Column        Dtype
---  ------        -----
 0   dr_no         int64
 1   date_rptd     datetime64[ns]
 2   date_occ      datetime64[ns]
 3   time_occ      object
 4   area          int64
 5   area_name     object
 6   rdistrict_no  int64
 7   crime_code    int64
 8   crime_desc    object
 9   mocodes       object
 10  vict_age      int64
 11  vict_sex      object
 12  vict_descent  object
 13  premise_code  float64
 14  premis_desc   object
 15  weapon_code   float64
 16  weapon_desc   object
 17  status        object
 18  status_desc   object
 19  crm_cd_1      float64
 20  crm_cd_2      float64
 21  crm_cd_3      float64
 22  crm_cd_4      float64
 23  location      object
 24  cross_street  object
 25  latitude      float64
 26  longitude     float64
dtypes: datetime64[ns](2), float64(8), int64(5), object(12)
memory usage: 646.4+ MB

In [10]:
#replacing letter code with corresponding ethnicity
ethnicity_mapping = {
    'A': 'Other Asian',
    'B': 'Black',
    'C': 'Chinese',
    'D': 'Cambodian',
    'F': 'Filipino',
    'G': 'Guamanian',
    'H': 'Hispanic/Latin/Mexican',
    'I': 'American Indian/Alaskan Native',
    'J': 'Japanese',
    'K': 'Korean',
    'L': 'Laotian',
    'O': 'Other',
    'P': 'Pacific Islander',
    'S': 'Samoan',
    'U': 'Hawaiian',
    'V': 'Vietnamese',
    'W': 'White',
    'X': 'Unknown',
    'Z': 'Asian Indian'
}
vict_ethnicity = []
for ethnicity in df['vict_descent']:
    vict_ethnicity.append(ethnicity_mapping.get(ethnicity))

#replacing letter code with corresponding sex
vict_sex = []
for sex in df['vict_sex']:
    if sex == 'M':
        vict_sex.append('Male')
    elif sex == 'F':
        vict_sex.append('Female')
    else:
        vict_sex.append('Unknown')

#replacing descent column with ethnicity column
df.rename(columns={'vict_descent': 'vict_ethnicity'}, inplace=True)
df['vict_ethnicity'] = vict_ethnicity
df['vict_sex'] = vict_sex

In [11]:
#checking missing values and dropping
list = []

for row in df.columns:
  columns = df.columns
  instances = df[row].count()
  unique = df[row].nunique()
  nulls = df[row].isnull().sum()
  duplicates = df[row].duplicated().sum()
  list.append([instances, unique, nulls, duplicates])

data_breakdown = pd.DataFrame(list, columns=['instances','unique','nulls','duplicates'], index = columns)
data_breakdown

                instances   unique    nulls  duplicates
dr_no             3138119  3098304        0       39815
date_rptd         3138119     5522        0     3132597
date_occ          3138119     5515        0     3132604
time_occ          3138119     1439        0     3136680
area              3138119       21        0     3138098
area_name         3138119       21        0     3138098
rdistrict_no      3138119     1314        0     3136805
crime_code        3138119      143        0     3137976
crime_desc        3138119      143        0     3137976
mocodes           2756484   755203   381635     2382915
vict_age          3138119      115        0     3138004
vict_sex          3138119        3        0     3138116
vict_ethnicity    2795218       19   342901     3138099
premise_code      3138049      329       70     3137789
premis_desc       3137343      319      776     3137799
weapon_code       1044048       80  2094071     3138038
weapon_desc       1044047       79  2094072     3138039
status            3138115        9        4     3138109
status_desc       3138119        6        0     3138113
crm_cd_1          3138098      150       21     3137968
crm_cd_2           211291      147  2926828     3137971
crm_cd_3             5907       67  3132212     3138051
crm_cd_4              169       12  3137950     3138106
location          3138119    84221        0     3053898
cross_street       511389    15665  2626730     3122453
latitude          3138119     5715        0     3132404
longitude         3138119     5155        0     3132964

In [12]:
#saving cleaned and standarized dataframe into a csv
df.to_csv('crime_data_2010-Present.csv', index=False)